modLoader="javafml"
loaderVersion="[47,)"  # для Forge 1.20.1
license="MIT"

[[mods]]
modId="dintegrate"
version="1.0.0"
displayName="Donate Integrate"
authors="Bohdan Ihnatenko"
description='''
Интеграция DonatePay с Minecraft-сервером.
Позволяет выполнять команды при получении донатов.
'''

[[dependencies.dintegrate]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="SERVER"

[[dependencies.dintegrate]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="SERVER"